# Project information
site_name: "Mind+ Official Documentation"
site_url: https://mindplus.cc
site_author: Mind+ Team
site_description: >-
     Mind+ Official Tutorial-Mind+

# Repository
repo_name: Mind+/Docs
repo_url: https://mindplus.cc
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2025 - 2029 Mind+ Team'

# Configuration

theme:
  name: material
  #custom_dir: overrides
  nav_style: dark
  features:
    - navigation.path  # Enable breadcrumbs

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.path
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - navigation.top
  
  
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico

  #icon:
    #logo: material/library
  logo: assets/images/Mindlogo.png

# Plugins
plugins:
  - search:
      lang: 
        - en
  - minify:
      minify_html: true
  - glightbox

# Hooks
# hooks:
  # - material/.overrides/hooks/translations.py

# Customization
# extra:
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  # social:
  #   - icon: fontawesome/solid/globe
  #     link: https://www.mindplus.com.cn/
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/UNIHIKER/unihiker-docs
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/UNIHIKER
  #   - icon: fontawesome/brands/facebook
  #     link: https://www.facebook.com/UNIHIKER
  #   - icon: fontawesome/brands/discord
  #     link: https://discord.gg/rvvfNCvBKv
#  alternate:
#    - name: Chinese
#      link: /zh/
#      lang: zh

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.snippets
  # - markdown.extensions.meta
  - attr_list 
  - md_in_html 

extra_css:
  - stylesheets/extra.css

nav:
  - Home: https://mindplus.cc/en.html
  - Download: https://mindplus.cc/en.html
  - Documentation:
      - Mind+ V2 Official Tutorial: index.md
      - 1.Quick Start:
          - 1.1 Mind+ Usage Guide: GettingStarted/UserGuide.md
          - 1.2 Mind+ Usage Tutorial: GettingStarted/UserTutorial.md
      - 2.General Features:
          - 2.1 Mind+ Introduction: SoftwareIntroduction//Introduction.md
          - 2.2 Software Installation:
              - 2.1.1 Windows: SoftwareIntroduction/Windows.md
              - 2.1.2 MacOS: SoftwareIntroduction/MacOS.md
              - 2.1.3 Linux: SoftwareIntroduction/Linux.md
              - 2.1.4 ReleaseLogs: SoftwareIntroduction/ReleaseLogs.md
              - 2.1.5 PreviousVersions: SoftwareIntroduction/PreviousVersions.md
      - 3.Coding:
          - 3.1 RealTime Mode:
              - 3Coding/31RealTimeMode/index.md
              - 3.1.1 Menu Bar: 3Coding/31RealTimeMode/311MenuBar.md
              - 3.1.2 Settings: 3Coding/31RealTimeMode/312Settings.md
              - 3.1.3 Functional Areas-Blocks:
                  - 3Coding/31RealTimeMode/313FunctionalAreasBlocks/index.md
                  - 3.1.3.1 Motion: 3Coding/31RealTimeMode/313FunctionalAreasBlocks/3131.md
                  - 3.1.3.2 Looks: 3Coding/31RealTimeMode/313FunctionalAreasBlocks/3132Looks.md
                  - 3.1.3.3 Sound: 3Coding/31RealTimeMode/313FunctionalAreasBlocks/3133Sounds.md
                  - 3.1.3.4 Events: 3Coding/31RealTimeMode/313FunctionalAreasBlocks/3134Events.md
                  - 3.1.3.5 Control: 3Coding/31RealTimeMode/313FunctionalAreasBlocks/3135Control.md
                  - 3.1.3.6 Sensing: 3Coding/31RealTimeMode/313FunctionalAreasBlocks/3136Sensing.md
                  - 3.1.3.7 Operators: 3Coding/31RealTimeMode/313FunctionalAreasBlocks/3137Operators.md
                  - 3.1.3.8 Variables: 3Coding/31RealTimeMode/313FunctionalAreasBlocks/3138Variables.md
                  - 3.1.3.9 My Blocks: 3Coding/31RealTimeMode/313FunctionalAreasBlocks/3139MyBlocks.md
              - 3.1.4 Functional area-Costumes: 3Coding/31RealTimeMode/313FunctionalAreaCostumes.md
              - 3.1.5 Function Area-Sounds: 3Coding/31RealTimeMode/315FunctionAreaSound.md
              - 3.1.6 Extension Area: 3Coding/31RealTimeMode/316ExtensionArea.md
              - 3.1.7 Programming Area: 3Coding/31RealTimeMode/317ProgrammingArea.md
              - 3.1.8 Stage Area: 3Coding/31RealTimeMode/318StageArea.md
              - 3.1.9 Sprite and background area: 3Coding/31RealTimeMode/319CharactersAndBackgroundArea.md
          - 3.2 Upload Mode:
              - 3Coding/32UploadMode/index.md
              - 3.2.1 Menu Bar: 3Coding/32UploadMode/321MenuBar.md
              - 3.2.2 Settings: 3Coding/32UploadMode/322Settings.md
              - 3.2.3 Functional Areas-Blocks:
                  - 3Coding/32UploadMode/323FunctionalAreasBlocks/index.md
                  - 3.2.3.1 Control: 3Coding/32UploadMode/323FunctionalAreasBlocks/3231Control.md
                  - 3.2.3.2 Operators: 3Coding/32UploadMode/323FunctionalAreasBlocks/3232Operators.md
                  - 3.2.3.3 Variables: 3Coding/32UploadMode/323FunctionalAreasBlocks/3233Variables.md
                  - 3.2.3.4 My Blocks: 3Coding/32UploadMode/323FunctionalAreasBlocks/3234MyBlocks.md
              - 3.2.4 Extension Area: 3Coding/32UploadMode/324ExtensionArea.md
              - 3.2.5 Programming Area: 3Coding/32UploadMode/325ProgrammingArea.md
              - 3.2.6 Code Display Area: 3Coding/32UploadMode/326CodeDisplayArea.md
              - 3.2.7 Serial Monitor: 3Coding/32UploadMode/327SerialMonitor.md
          - 3.3 Python Block Mode:
              - 3Coding/33PythonBlockMode/index.md
              - 3.3.1 Menu Bar: 3Coding/33PythonBlockMode/331MenuBar.md
              - 3.3.2 Settings: 3Coding/33PythonBlockMode/332Settings.md
              - 3.3.3 Functional Areas - Modules:
                  - 3Coding/33PythonBlockMode/333FunctionalAreas/index.md
                  - 3.3.3.1 Control: 3Coding/33PythonBlockMode/333FunctionalAreas/3331Control.md
                  - 3.3.3.2 Operators: 3Coding/33PythonBlockMode/333FunctionalAreas/3332Operators.md
                  - 3.3.3.3 Number: 3Coding/33PythonBlockMode/333FunctionalAreas/3333Number.md
                  - 3.3.3.4 Text: 3Coding/33PythonBlockMode/333FunctionalAreas/3334Text.md
                  - 3.3.3.5 Variables: 3Coding/33PythonBlockMode/333FunctionalAreas/3335Variables.md
                  - 3.3.3.6 My Blocks: 3Coding/33PythonBlockMode/333FunctionalAreas/3336MyBlocks.md
                  - 3.3.3.7 Advanced Types: 3Coding/33PythonBlockMode/333FunctionalAreas/3337AdvancedTypes.md
                  - 3.3.3.8 Python: 3Coding/33PythonBlockMode/333FunctionalAreas/3338Python.md
              - 3.3.4 Functional Areas - Asset: 3Coding/33PythonBlockMode/334FunctionalAreasResourceFiles.md
              - 3.3.5 Extension Area: 3Coding/33PythonBlockMode/334ExtensionArea.md
              - 3.3.6 Programming Area: 3Coding/33PythonBlockMode/335ProgrammingArea.md
              - 3.3.7 Code Display Area: 3Coding/33PythonBlockMode/336CodeDisplayArea.md
              - 3.3.8 Terminal display area: 3Coding/33PythonBlockMode/337SerialMonitor.md
          - 3.4 Micropython Block Mode:
              - 3Coding/34MicropythonBlockMode/index.md
              - 3.4.1 Menu Bar: 3Coding/34MicropythonBlockMode/341MenuBar.md
              - 3.4.2 Settings: 3Coding/34MicropythonBlockMode/342Settings.md
              - 3.4.3 Functional Areas - Modules:
                  - 3Coding/34MicropythonBlockMode/343FunctionalAreas/index.md
                  - 3.4.3.1 Control: 3Coding/34MicropythonBlockMode/343FunctionalAreas/3431Control.md
                  - 3.4.3.2 Operators: 3Coding/34MicropythonBlockMode/343FunctionalAreas/3432Operators.md
                  - 3.4.3.3 Number: 3Coding/34MicropythonBlockMode/343FunctionalAreas/3433Number.md
                  - 3.4.3.4 Text: 3Coding/34MicropythonBlockMode/343FunctionalAreas/3434Text.md
                  - 3.4.3.5 Variables: 3Coding/34MicropythonBlockMode/343FunctionalAreas/3435Variables.md
                  - 3.4.3.6 My Blocks: 3Coding/34MicropythonBlockMode/343FunctionalAreas/3436MyBlocks.md
                  - 3.4.3.7 Advanced Types: 3Coding/34MicropythonBlockMode/343FunctionalAreas/3437AdvancedTypes.md
              - 3.4.4 Functional Areas - Asset: 3Coding/34MicropythonBlockMode/344FunctionalAreasAsset.md
              - 3.4.5 Extension Area: 3Coding/34MicropythonBlockMode/344ExtensionArea.md
              - 3.4.6 Programming Area: 3Coding/34MicropythonBlockMode/345ProgrammingArea.md
              - 3.4.7 Code Display Area: 3Coding/34MicropythonBlockMode/346CodeDisplayArea.md
              - 3.4.8 Terminal Display Area: 3Coding/34MicropythonBlockMode/347TerminalDisplayArea.md
          - 3.5 Micropython Code Mode:
              - 3Coding/35MicropythonCodeMode/index.md
              - 3.5.1 Menu Bar: 3Coding/35MicropythonCodeMode/351MenuBar.md
              - 3.5.2 Settings: 3Coding/35MicropythonCodeMode/352Settings.md
              - 3.5.3 File Area: 3Coding/35MicropythonCodeMode/353FileArea.md
              - 3.5.4 Programming Area: 3Coding/35MicropythonCodeMode/354ProgrammingArea.md
              - 3.5.5 Terminal Display Area: 3Coding/35MicropythonCodeMode/355TerminalDisplayArea.md
          - 3.6 Python Code Model:
              - 3Coding/31RealTimeMode/PythonCodeModel/index.md
      - 4.Model:
          - 4.1 Basic Description:
              - 4.1.1 Introduction: AITools/Basic_description/introduction/introduction.md
              - 4.1.2 Quick Experience: AITools/Basic_description/quick_start/quick-start.md
              - 4.1.3 Model Training: AITools/Basic_description/model_training/model-training.md
              - 4.1.4 Model Deploy: AITools/Basic_description/model_deployment/model-deployment.md
              - 4.1.5 Real-time Result Push: AITools/Basic_description/real_time_push/real-time-push.md
          - 4.2 Detailed Description:
              - 4.2.1 【Image Classification】 Quick Experience: AITools/Detailed_explanation/image_classification/quick_experience/quick-experience.md
              - 【Image Classification】 Advanced Mode: AITools/Detailed_explanation/image_classification/professional_mode/professional-mode.md
              - 4.2.2 【Object Detection】 Quick Experience: AITools/Detailed_explanation/object_detection/quick_experience/quick-experience.md
              - 【Object Detection】 Advanced Mode: AITools/Detailed_explanation/object_detection/professional_mode/professional-mode.md
              - 4.2.3 【Instance Segmentation】 Quick Experience: AITools/Detailed_explanation/instance_segmentation/quick_experience/quick-experience.md
              - 【Instance Segmentation】 Advanced Mode: AITools/Detailed_explanation/instance_segmentation/professional_mode/professional-mode.md
              - 4.2.4 【Temporal Pattern Recognitionn】 Quick Experience: AITools/Detailed_explanation/time_series_recognition/quick_experience/quick-experience.md
              - 【Temporal Pattern Recognition】 Advanced Mode: AITools/Detailed_explanation/time_series_recognition/professional_mode/professional-mode.md
              - 4.2.5 【Speech Classification】 Quick Experience: AITools/Detailed_explanation/speech_classification/quick_experience/quick-experience.md
              - 4.2.6 【Text Classification】 Quick Experience: AITools/Detailed_explanation/text_classification/quick_experience/quick-experience.md
              - 4.2.7 【Pose Classification】 Quick Experience: AITools/Detailed_explanation/pose_classification/quick_experience/quick-experience.md
  - FAQ:
      - 1. General Settings FAQs:
          - FAQ/GeneralSettingsFAQs/index.md
          - What should I do if I can't find the login page?: FAQ/GeneralSettingsFAQs/WhatShouldIDoIfICanTFindTheLoginPage.md
          - Fix "Please Connect to Mind+Link First" Error in Extension Library: FAQ/GeneralSettingsFAQs/FixPleaseConnectToMindLinkFirstErrorInExtensionLibrary.md
      - FAQ: FAQ/index.md
      - 2. Coding:
          - FAQ/Coding/Coding/index.md
          - 2.1 RealTime Mode:
              - FAQ/Coding/RealTimeMode/index.md
              - RealTime Mode Issues: FAQ/Coding/RealTimeMode/runtime-error.md
          - 2.2 Upload Mode:
              - FAQ/Coding/UploadMode/index.md
              - What should I do if I get a K10 character quotation mark error?: FAQ/Coding/UploadMode/WhatShouldIDoIfIGetAK10CharacterQuotationMarkError.md
              - How do I restore the firmware in upload mode?: FAQ/Coding/UploadMode/HowDoIRestoreTheFirmwareInUploadMode.md
              - Fix "Failed to Load Extension" When Downloading Mainboard Driver: FAQ/Coding/UploadMode/FixFailedToLoadExtensionWhenDownloadingMainboardDriver.md
          - 2.3 Python Block Mode:
              - FAQ/Coding/PythonBlockMode/index.md
              - Python Environment Not Found?: FAQ/Coding/PythonBlockMode/fix-python-not-found-error.md
          - 2.4 MicroPython block Mode:
              - FAQ/Coding/MicroPythonBlockMode/index.md
          - 2.5 MicroPython Code Mode:
              - FAQ/Coding/Coding/MicroPythonCodeMode/index.md
          - 2.6 Python Code Mode:
              - FAQ/Coding/Coding/PythonCodeMode/index.md
      - 3. Model:
          - FAQ/Model/index.md
          - How to Fix "No module named 'model_mp_io'" Error: FAQ/Model/HowToFixNoModuleNamedModelMpIoError.md
          - 'How to Fix "pyenv: command not found" Error': FAQ/Model/HowToFixPyenvCommandNotFoundError.md
      - 4. View:
          - FAQ/View/index.md
      - 5. Extension:
          - FAQ/Coding/RealTimeMode/Extension/index.md
          - How to Add an Extension Library: FAQ/Coding/RealTimeMode/Extension/HowToAddAnExtensionLibrary.md
          - How to Fix Extension Library Download Failure: FAQ/Coding/RealTimeMode/Extension/HowToFixExtensionLibraryDownloadFailure.md
  - Extension:
      - Extension/index.md
      - RealTime Mode:
          - Extension/RealTimeMode/index.md
          - Image Classification: Extension/RealTimeMode/ImageClassification.md
          - Object Detection: Extension/RealTimeMode/ObjectDetection.md
          - Instance Segmentation: Extension/RealTimeMode/InstanceSegmentation.md
          - Pose Classification: Extension/RealTimeMode/PoseClassification.md
          - Speech Classification: Extension/RealTimeMode/SpeechClassification.md
          - Text Classification: Extension/RealTimeMode/TextClassification.md
      - UploadMode:
          - Extension/UploadMode/index.md
          - Temporal Pattern Recognition: Extension/UploadMode/TemporalPatternRecognition.md
      - Python Block Mode:
          - Extension/PythonBlockMode/index.md
          - Model Training and Inference Library: Extension/PythonBlockMode/ModelTrainingAndInferenceLibrary.md
  - Community: https://community.dfrobot.com/
  - About Us: AboutUs/index.md
  - Mind+ V1.x Documentation: https://mindplus.dfrobot.com